# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/qureshkd/Documents/Vivado_Tutorial/Adder/Adder.cache/wt [current_project]
set_property parent.project_path /home/qureshkd/Documents/Vivado_Tutorial/Adder/Adder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib /home/qureshkd/Documents/Vivado_Tutorial/Adder/Adder.srcs/sources_1/new/CarryLookAheadAdder.vhd
synth_design -top CarryLookAheadAdder -part xc7vx485tffg1157-1
write_checkpoint -noxdef CarryLookAheadAdder.dcp
catch { report_utilization -file CarryLookAheadAdder_utilization_synth.rpt -pb CarryLookAheadAdder_utilization_synth.pb }
